#!/bin/bash

central_local_path="$UTILUX_CENTRAL_DIR"
central_backup_path="$UTILUX_CENTRAL_BACKUP_DIR"

if [ -z "$central_local_path" ]; then
    echo "Please configure UTILUX_CENTRAL_DIR through the utilux-config command"
    exit 1
fi
if [ -z "$central_backup_path" ]; then
    echo "Please configure UTILUX_CENTRAL_BACKUP_DIR through the utilux-config command"
    exit 1
fi

if [[ ! "$central_local_path" == */ ]]; then
    echo "Error : UTILUX_CENTRAL_DIR must ends with a / (got [$central_local_path])"
    exit 1
fi

if [[ ! "$central_backup_path" == */ ]]; then
    echo "Error : UTILUX_CENTRAL_BACKUP_DIR must ends with a / (got [$central_backup_path])"
    exit 1
fi

if [ ! -d "$central_local_path" ]; then
    echo "Error : UTILUX_CENTRAL_DIR ($central_local_path) is not a directory !"
    exit 1
fi

if [ ! -d "$central_backup_path" ]; then
    echo "Error : UTILUX_CENTRAL_BACKUP_DIR ($central_backup_path) is not a directory !"
    exit 1
fi


if [ -z "$(which rsync)" ]; then 
    echo "Error: rsync program not found"
    exit 2
fi

echo "This command shall be run"
echo "  > rsync -avh --delete --dry-run --progress \"$central_local_path\" \"$central_backup_path\""
echo

read -p "Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Bye!"
    exit 3
fi


echo "Running dry-run first"
rsync -avh --delete --dry-run --progress "$central_local_path" "$central_backup_path"

read -p "Run the command without --dryrun ? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rsync -avh --delete --progress "$central_local_path" "$central_backup_path"
    exit 0
fi

exit 3

