#!/bin/sh

cd $UTILUX_PATH && \
    git pull && \
    echo "Utilux updated !"

utilux-prompt --prompt "Launch utilux-update-config ?" && utilux-update-config
utilux-prompt --prompt "Launch utilux-setup ?" && utilux-setup