#!/bin/sh

binName="$1"

if [ ! -f "$binName" ]
then
    echo "Cannot install, [$binName] is not a file"
    exit 1
fi

binName="$(realpath "$1")"

if [ ! -f "$binName" ]
then
    echo "Cannot install, [$binName] is not a file"
    exit 1
fi

targetBinName="$UTILUX_BIN_PATH/$(basename $binName)"

if [ -f "$targetBinName" ]
then
    echo "[$targetBinName] already exists !"
    exit 1
fi

echo "Linking symlink $targetBinName to $binName"
ln -s "$binName" "$targetBinName"