#!/bin/bash





function makeDirectoryIfInexistant()
{
    DIR=$1
    if [ ! -d $DIR ]
    then
        echo "Making repos directory $DIR"
        mkdir -p $DIR
    fi
}



function ensureProgramIsInstalled()
{
    PROG=$1
    if [ -z $(which $PROG) ]
    then
        echo "$PROG is needed to work with json"
        echo "you can install it with"
        echo ""
        echo "sudo apt install $PROG"
        exit 1
    fi
}










function getGitApiTokenPath()
{
    echo "$GITUTILS_CONFIG_PATH/api_key"
}

function getGitApiToken()
{
    GITUTILS_API_KEY_PATH=$(getGitApiTokenPath)

    if [ ! -f $GITUTILS_API_KEY_PATH ]
    then
        echo "Please first register a key with git-utils register-key <your_api_key>"
        exit 1
    fi

    echo $(<$GITUTILS_API_KEY_PATH)
}

function registerToken()
{
    echo "Registering $1 as api-key"

    GITUTILS_API_KEY_PATH=$(getGitApiTokenPath)

    echo $1 > $GITUTILS_API_KEY_PATH
    echo "Done."
}






function createRepo()
{
    ensureProgramIsInstalled "jq"

    REPO_NAME=$1
    API_TOKEN=$(getGitApiToken)


    echo "Create repo $REPO_NAME..."

    OUTPUT=$(curl -L -s \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $API_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/user/repos \
      -d "{\"name\":\"$REPO_NAME\",\"private\":true}")

    URL=$(echo "$OUTPUT" | jq -r ".html_url")

    if [ "$URL" = "null" ]
    then
        echo "URL NOT FOUND !"
        echo "Please ensure that there is no error with curl"
        echo "Here is the curl output"
        echo "$OUTPUT"
        exit 1
    fi

    REPO_NAME=$(echo "$OUTPUT" | jq -r ".full_name")
    REPO_PATH="$GITUTILS_REPOS_PATH/$REPO_NAME"
    OG_PWD=$(pwd)

    git clone $URL $REPO_PATH
    cd $REPO_PATH


    read -p "Add Sharp Framework (y/n) ? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git submodule add https://github.com/yonis-savary/sharp-php Sharp >/dev/null 2>&1
        cp -r Sharp/Core/Server/* . >/dev/null 2>&1
        php do fill-configuration >/dev/null 2>&1

        git add * >/dev/null 2>&1
        git commit -a -m "Added Sharp-PHP Framework" >/dev/null 2>&1

        echo "Added Sharp framework to your repo !"

        read -p "Add Sharp Extensions Utilities (y/n) ? " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            git submodule add https://github.com/yonis-savary/sharp-extensions SharpExtensions >/dev/null 2>&1

            php do enable-application SharpExtensions/AssetsKit SharpExtensions/LazySearch SharpExtensions/RemindMe >/dev/null 2>&1
            php do fill-configuration >/dev/null 2>&1

            git add * >/dev/null 2>&1
            git commit -a -m "Added Sharp-Extensions Toolkit" >/dev/null 2>&1

            echo "Added SharpExtensions toolkit to your repo !"
        fi

        git push >/dev/null 2>&1
    fi

    read -p "Create symlink on your desktop (y/n) ? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        REPO_BASENAME=$(basename $REPO_NAME)
        REPO_SYMLINK="$HOME_PATH/Desktop/$REPO_BASENAME"

        if [ -L $REPO_SYMLINK ]
        then
            echo "It seems that $REPO_SYMLINK already exists !"
            echo "Please remove it before creating it again"
            echo "rm $SYMLINK_PATH"
            echo "ln -s \"$REPO_PATH\" \"$REPO_SYMLINK\""
        else
            ln -s "$REPO_PATH" "$REPO_SYMLINK"
            echo "Created symlink at $REPO_SYMLINK !"
        fi

    fi

    echo
    echo "---------------------------"
    echo "Repo $REPO_NAME successfuly created & pushed !"
    echo "Url  : $URL"
    echo "Path : $REPO_PATH"
    echo "---------------------------"
    echo

    cd $OG_PWD
}



function enableCredentialCache()
{
    git config --global credential.helper cache
    echo "Enabled credential helper cache !"
}

function disableCredentialCache()
{
    git config --global --unset credential.helper
    echo "Unset credential helper cache !"
}




function createDesktopSymlink()
{
    REPO_NAME=$1

    if [ ! -z "$REPO_NAME" ]
    then
        REPO_BASENAME=$(basename $REPO_NAME)
        SYMLINK_TARGET="$GITUTILS_REPOS_PATH/$REPO_NAME"
        SYMLINK_PATH="$HOME_PATH/Desktop/$REPO_BASENAME"
    else
        SYMLINK_TARGET=$GITUTILS_CONFIG_PATH
        SYMLINK_PATH="$HOME_PATH/Desktop/repositories"
    fi

    if [ ! -d $SYMLINK_TARGET ]
    then
        echo "Error ! Symlink target $SYMLINK_TARGET does not exists"
        exit 1
    fi

    if [ -L $SYMLINK_PATH ]
    then
        echo "It seems that $SYMLINK_PATH already exists !"
        echo "Please remove it before creating it again"
        echo "rm $SYMLINK_PATH"
        exit 1
    fi

    ln -s "$SYMLINK_TARGET" "$SYMLINK_PATH"
    echo "Created symlink $SYMLINK_PATH"
    echo "leading to $SYMLINK_TARGET"
}



function cloneAllRepositories()
{
    API_TOKEN=$(getGitApiToken)

    RES=$(curl -L -s \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $API_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/user/repos)

    URL=$(echo "$RES" | jq -r .[].full_name | tail -n 3)

    if [ "$URL" = "null" ]
    then
        echo "URLs NOT FOUND !"
        echo "Please ensure that there is no error with curl"
        echo "Here is the curl output"
        echo "$OUTPUT"
        exit 1
    fi

    for REPO_NAME in $URL
    do
        echo "Cloning $REPO_NAME"

        REPO_DIRECTORY="$GITUTILS_REPOS_PATH/$REPO_NAME"

        if [ -d $REPO_DIRECTORY ]
        then
            echo "Skipping, $REPO_DIRECTORY directory already exists"
        else
            git clone "https://github.com/$REPO_NAME" "$REPO_DIRECTORY" --recursive
        fi

        echo

    done

}



function displayHelp()
{
    echo "git-utils : collection of tools to make project management easier"
    echo ""
    echo "Available Commands"
    echo
    echo " make <PROJECT_NAME>"
    echo "     Make a repository, can install Sharp & SharpExtensions if wanted"
    echo
    echo " clone-all"
    echo "     Clone all of your repositories"
    echo
    echo " register-key <API_KEY>"
    echo "     Register a new GitHub api token"
    echo
    echo " get-key"
    echo "     Get the registered GitHub api token"
    echo
    echo " enable-cache"
    echo "     Enable the credential store cache"
    echo
    echo " disable-cache"
    echo "     Disable the credential store cache"
    echo
    echo " symlink"
    echo "     Create a symlink on your desktop to the repositories directory"
    echo
    echo " symlink <Author/Repo>"
    echo "     Create a symlink on your desktop to the repository directory"
    echo
    echo " help"
    echo "     Display this help message"
}




HOME_PATH=$(realpath ~)
GITUTILS_CONFIG_PATH="$HOME_PATH/.config/utilux/git-utils"
GITUTILS_REPOS_PATH="$HOME_PATH/.config/utilux/git-utils/repositories"

makeDirectoryIfInexistant $GITUTILS_CONFIG_PATH
makeDirectoryIfInexistant $GITUTILS_REPOS_PATH


COMMAND=$1

case $COMMAND in
    make)
        createRepo $2
    ;;

    register-key)
        registerToken $2
    ;;

    get-key)
        echo "Here's your api token:"
        echo ""
        echo "    $(getGitApiToken)"
        echo ""
    ;;

    enable-cache)
        enableCredentialCache
    ;;

    disable-cache)
        disableCredentialCache
    ;;

    symlink)
        createDesktopSymlink $2
    ;;

    help)
        displayHelp
    ;;

    clone-all)
        cloneAllRepositories
    ;;

    *)
        echo "Unknown command '$1'"
        exit 1
    ;;
esac

echo

exit 0