#!/bin/bash
echo "All of these branches will be force-removed"
git branch --merged | grep -v -E "master|main|develop|^\+"

read -p "Proceed ? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    git branch --merged | grep -v -E "master|main|develop|^\+" | xargs git branch -D;
fi

