#!/bin/bash

function installCodeExtention()
{
    res=$(code --install-extension "$1" 2>&1);
    already_installed=$(echo $res | grep 'already installed' | wc -l);

    if (( $already_installed > 0 ))
    then
        echo -e " - \e[32m[INSTALLED]\e[0m $1 $alias";
    else
        echo "$res";
    fi
    echo -ne "\e[0m";
}

function isInstalled()
{
    missing=$(dpkg -s "$1" 2>&1 | grep "not installed" | wc -l)

    if (( $missing > 0 ))
    then
        if [ ! -z "$(which $1)" ];
        then
            return 1;
        fi
        return 0;
    fi
    return 1;
}

function checkInstalled()
{
    isInstalled "$1"
    installed=$?

    if (( $installed == 0))
    then
        echo -e " - \e[31m[MISSING]\e[0m $1 $alias";
    else
        echo -e " - \e[32m[OK]\e[0m $1 $alias";
    fi
    echo -ne "\e[0m";
}

echo "Languages/tools to install";
checkInstalled "git";
checkInstalled "php8.3";
checkInstalled "php8.3-mysql";
checkInstalled "composer"
checkInstalled "sqlite3";
checkInstalled "nodejs";
checkInstalled "lessc"
checkInstalled "less";
checkInstalled "java";
checkInstalled "native-image";
checkInstalled "ffmpeg";

echo "Software to install";
checkInstalled "filezilla";
checkInstalled "code";
checkInstalled "firefox";

echo "Office Softwares"
checkInstalled "libreoffice";
checkInstalled "gimp";
checkInstalled "inkscape";

echo "DVD/Music Utilities"
checkInstalled "easytag";
checkInstalled "asunder";


isInstalled 'code';
if [ "$?" == "1" ]
then
    echo "Checking code extensions..."
    installCodeExtention "GitHub.github-vscode-theme"
    installCodeExtention "PKief.material-icon-theme"
    installCodeExtention "zhuangtongfa.material-theme"
    installCodeExtention "bmewburn.vscode-intelephense-client"
    installCodeExtention "mechatroner.rainbow-csv"
    installCodeExtention "shardulm94.trailing-spaces"
    installCodeExtention "streetsidesoftware.code-spell-checker"
    installCodeExtention "redhat.vscode-xml"

    echo "Checking code extensions for java"
    installCodeExtention "vscjava.vscode-java-debug"
    installCodeExtention "vscjava.vscode-java-pack"
    installCodeExtention "vscjava.vscode-gradle"
    installCodeExtention "VisualStudioExptTeam.vscodeintellicode"
    installCodeExtention "VisualStudioExptTeam.intellicode-api-usage-examples"
    installCodeExtention "redhat.java"
    installCodeExtention "vscjava.vscode-maven"
    installCodeExtention "vscjava.vscode-java-dependency"
    installCodeExtention "vscjava.vscode-java-test"
fi