#!/bin/bash

popacode_path="$1"
popacode_port="$2"

if [ -z $popacode_path ]; then popacode_path="."; fi
if [ -z $popacode_port ]; then popacode_port="5000"; fi

if [ ! -d $popacode_path ]
then
    echo "[$popacode_path] directory does not exists !"
    exit 1
fi

cd $popacode_path
code .

if [ -d "Public" ]; then cd "Public"; fi
if [ -d "public" ]; then cd "public"; fi
if [ -d "htdocs" ]; then cd "htdocs"; fi

echo "Starting web server at [$(pwd)] on port [$popacode_port]";
firefox localhost:$popacode_port &
php -S 0.0.0.0:$popacode_port
