#!/bin/bash

popacode_path="$1"

if [ -z $popacode_path ]; then popacode_path="."; fi

if [ ! -d $popacode_path ]
then
    echo "[$popacode_path] directory does not exists !"
    exit 1
fi

cd $popacode_path
code .
