#!/bin/bash

echo "utilux                  - This help file"
echo "utilux-setup            - Check if base programs / VSC extensions are installed "
echo "utilux-update           - Utilux self update tool"
echo "utilux-install-code     - Install or update Visual Studio Code (from official website)"
echo
echo "utilux-git              - Repository management tool"
echo "utilux-install          - Install utilux into your .bashrc"
echo "utilux-lf               - Transform crlf into lf in a directory"
echo "utilux-share [FILENAME] - Start a python web server to share given file"
echo
echo "gx - git utils, type gx for more"
echo "gx - docker compose utils, type dx for more"