#!/bin/bash

function installCodeExtention()
{
    res=$(code --install-extension "$1" 2>&1);
    already_installed=$(echo $res | grep 'already installed' | wc -l);

    if (( $already_installed > 0 ))
    then
        echo -e " - \e[32m[INSTALLED]\e[0m $1 $alias";
    else
        echo "$res";
    fi
    echo -ne "\e[0m";
}

function isInstalled()
{
    missing=$(dpkg -s "$1" 2>&1 | grep "not installed" | wc -l)

    if (( $missing > 0 ))
    then
        if [ ! -z "$(which $1)" ];
        then
            return 1;
        fi
        return 0;
    fi
    return 1;
}

function checkInstalled()
{
    isInstalled "$1"
    installed=$?

    if (( $installed == 0))
    then
        echo -e " - \e[31m[MISSING]\e[0m $1 $alias";
    else
        echo -e " - \e[32m[OK]\e[0m $1 $alias";
    fi
    echo -ne "\e[0m";
}

echo "Languages/tools to install";
checkInstalled "git";
checkInstalled "php8.3";
checkInstalled "php8.3-mysql";
checkInstalled "composer"
checkInstalled "sqlite3";
checkInstalled "nodejs";
checkInstalled "lessc"
checkInstalled "less";
checkInstalled "java";
checkInstalled "mvn";
checkInstalled "native-image";
echo

echo "Software to install";
checkInstalled "filezilla";
checkInstalled "code";
checkInstalled "firefox";
checkInstalled "ffmpeg";
echo

echo "Office Softwares"
checkInstalled "libreoffice";
checkInstalled "gimp";
checkInstalled "inkscape";
echo

echo "DVD/Music Utilities"
checkInstalled "easytag";
checkInstalled "asunder";
echo


isInstalled 'code';
if [ "$?" == "1" ]
then
    echo "Checking code extensions..."
    installCodeExtention "amiralizadeh9480.laravel-extra-intellisense"
    installCodeExtention "bmewburn.vscode-intelephense-client"
    installCodeExtention "bradlc.vscode-tailwindcss"
    #installCodeExtention "cjhowe7.laravel-blade"
    installCodeExtention "eamodio.gitlens"
    installCodeExtention "github.github-vscode-theme"
    installCodeExtention "gruntfuggly.todo-tree"
    installCodeExtention "irongeek.vscode-env"
    installCodeExtention "johnpapa.vscode-peacock"
    installCodeExtention "mechatroner.rainbow-csv"
    installCodeExtention "mhutchie.git-graph"
    installCodeExtention "ms-azuretools.vscode-docker"
    installCodeExtention "ms-vscode-remote.remote-containers"
    installCodeExtention "mujichok.vscode-project-name-in-statusbar"
    installCodeExtention "pkief.material-icon-theme"
    #installCodeExtention "redhat.java"
    #installCodeExtention "redhat.vscode-xml"
    installCodeExtention "shardulm94.trailing-spaces"
    #installCodeExtention "shufo.vscode-blade-formatter"
    installCodeExtention "streetsidesoftware.code-spell-checker"
    installCodeExtention "usernamehw.errorlens"
    installCodeExtention "visualstudioexptteam.intellicode-api-usage-examples"
    installCodeExtention "visualstudioexptteam.vscodeintellicode"
    #installCodeExtention "vscjava.vscode-gradle"
    #installCodeExtention "vscjava.vscode-java-debug"
    #installCodeExtention "vscjava.vscode-java-dependency"
    #installCodeExtention "vscjava.vscode-java-pack"
    #installCodeExtention "vscjava.vscode-java-test"
    #installCodeExtention "vscjava.vscode-maven"
    installCodeExtention "vue.volar"
    installCodeExtention "yoavbls.pretty-ts-errors"
    installCodeExtention "zhuangtongfa.material-theme"
    echo
fi
