#!/bin/sh
branch_name="$1"
ticket_regex='^[A-Z]+-[0-9]+$'


if echo "$branch_name" | grep -E "$ticket_regex" > /dev/null; then

    echo "Making branch for ticket $branch_name"

    if [ ! -z "$UTILUX_JIRA_HOST" ]
    then
        output=$(curl -s --request GET \
            --url "$UTILUX_JIRA_HOST/issue/$branch_name?fields=summary,issuetype" \
            --user "$UTILUX_JIRA_EMAIL:$UTILUX_JIRA_TOKEN" \
            --header 'Accept: application/json'
        )

        branch_type="feat"
        issue_type=$(echo "$output" | jq '.fields.issueType.name' -r )
        if [ "$(echo "$issue_type" | grep -ciE "bug" )" ]
        then
            branch_type="fix"
        fi

        title=$(
            echo "$output" | \
            jq '.fields.summary' -r | \
            iconv -f utf8 -t ascii//TRANSLIT | \
            tr '[:upper:]' '[:lower:]' | \
            perl -pe "s/[a-z]\'//g" | \
            perl -pe "s/.+?\[.+?\]//g" | \
            perl -pe "s/[^0-9a-z]/ /g" | \
            perl -pe "s/^\s|\s+\$//g" | \
            perl -pe "s/\b\w{,3}\b//g" | \
            perl -pe "s/ +/-/g"
        )
        branch_name="$branch_type/$branch_name/$title"
    else
        echo "Jira is not configured on your utilux setup"
    fi

fi

echo "Making branch $branch_name"

git checkout -b "$branch_name" "origin/$(gxb)"