#!/bin/sh
# git init - make your projet fresh to start something

set -euo pipefail

# Couleurs pour un affichage stylé

echo "⚠️  Warning ! This command will perform a git reset --hard"
read -p "Proceed ? [y/N]:" -n 1 -r
echo

if ! echo "$REPLY" | grep -E '^[Yy]$' > /dev/null; then
    echo "❌ Aborted."
    exit 1
fi

echo
echo "🧹 Cleaning up your repo..."
git reset --hard
git clean -fd

echo
echo "🔁 Syncing remote branch with local..."
git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
    if [ "$branch" = "main" ]; then
        continue
    fi

    if git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
        git branch --set-upstream-to="origin/$branch" "$branch"
        echo "🔗 Upstream defined for ${branch} → origin/${branch}"
    else
        echo "⚠️  No remote branch for ${branch}"
    fi

done

echo
echo "📥 Retrieving missing work..."
gxf
git pull --all


echo
echo "✅ Your repo is now ready to work with !"