#!/bin/sh

branch_name="$1"

if [ -f '.git/refs/heads/$branch_name' ]; then 
    echo "$branch_name"
    exit 0
fi

true_branch_name=$(git --no-pager branch  | sed -e 's/^[^a-zA-Z]*//g' | grep "$branch_name" --color=never | head -n1)

if [ -z "$true_branch_name" ]; then 
    echo $branch_name
    exit 0
fi

echo $true_branch_name


