#!/bin/sh

protected_branches="master|main|develop"
merged_branches=$(git branch --merged | grep -vE "\*|$protected_branches" | sed 's/^ *//')

if [ -z "$merged_branches" ]
then
  echo "✅ No merged branches to delete."
  exit 0
fi

if [ "$1" != "--force" -a "$1" != "-y" ]
then
  if ! utilux-prompt --prompt "⚠️ The following branches are merged and will be force-deleted:\n$merged_branches\n\nProceed with deletion ?"; then 
    echo "⚠️ The following branches are merged and will be force-deleted:\n\n$merged_branches\n\nProceed with deletion ?"
    echo "❌ Aborted."
    exit 0
  fi
fi

echo "$merged_branches" | xargs -n 1 git branch -D