#!/bin/sh

followed_branch="$1"
auto_yes=false

for arg in "$@"; do
  case $arg in
    -y|--yes)
      auto_yes=true
      ;;
    *)
      followed_branch="$arg"
      ;;
  esac
done


if [ -z "$followed_branch" ]; then 
	followed_branch="develop"
fi

if [ "$auto_yes" != true ]; then
	if ! utilux-prompt --prompt "About to execute : git pull --rebase origin $followed_branch\n\nProceed ?"; then
		echo "Aborted."
		exit 1
	fi
fi

echo "Proceeding with: git pull --rebase origin $followed_branch"
git pull --rebase origin "$followed_branch"