#!/bin/bash

followed_branch="$1"
if [ -z "$followed_branch" ]; then 
    followed_branch="develop"
fi

echo "About to execute : git pull --rebase origin $followed_branch"
read -p "Proceed ? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    git pull --rebase origin $followed_branch
fi
